#!/usr/bin/env bash

declare filePath
filePath="$(pwd)/.env"

if [[ -f "${filePath}" ]]; then
  # shellcheck source=./.env
  source "${filePath}"
  echo "File \"${filePath}\" exists"
fi

build_binary() {
  local dir os_type output_path
  dir=$1
  os_type="$(uname -o)"

  case "${os_type}" in
    Darwin | GNU/Linux)
      output_path=/opt/artifacts/go-calculator
      ;;
    *)
      echo -e "Unsupported OS. supported OS includes just: Linux and Darwin"
      return 1
      ;;
  esac

  go build -o "${output_path}" -buildmode=exe "${dir}" && gzip "${output_path}"
  ls -lA /opt/artifacts
}

create_relase() {

  data=(
    "{\"tag_name\":\"${TAG}\",\"name\":\"go-calculator@${TAG}\",\"body\":\"go-calculator release for tag ${TAG}\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":true,\"make_latest\":true}"
  )

  curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${GH_TOKEN}" \
    "https://api.github.com/repos/${REPOSITORY}/releases" \
    -d "${data[0]}" 2>&1
}

get_last_release() {
  declare -g release_id tag_name

  release_id="$(
    curl -L \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${GH_TOKEN}" \
      "https://api.github.com/repos/${REPOSITORY}/releases/latest" 2>/dev/null >&1
  )"

  [[ -z "${release_id}" ]] && exit 1

  tag_name="$(printf '%s\n' "${release_id}" | grep 'tag_name' | cut -d: -f2,3 | sed 's/[^\b],$//' | tr -d \")"
  release_id="$(printf '%s\n' "${release_id}" | grep 'upload_url' | cut -d: -f2,3 | sed 's/[^\b],$//' | tr -d \")"
  echo "${release_id}"
  echo "${tag_name}"
}

upload_release_asset() {
  curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${GH_TOKEN}" \
    -H "Content-Type: application/octet-stream" \
    "https://uploads.github.com/repos/${REPOSITORY}/releases/${release_id}/assets?name=${BINARY}" \
    --data-binary "${BINARY}" 2>&1
}
