name: Build go-calculator

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.21"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: dependencies
        run: go get

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --no-config --out-format github-actions --disable-all --enable errcheck
          install-mode: goinstall

      - name: Build
        env:
          dir: ${{ github.workspace }}
        run: |
          chmod +x ${{ env.dir }}/build-package
          . ${{ env.dir }}/build-package ${{ env.dir }}
          
      - name: uploadArtifact
        uses: actions/upload-artifact@v3
        with:
          name: go-calculator
          path: /opt/artifacts/go-calculator
